apiVersion: apps/v1
kind: Deployment
metadata:
  name: wheelsun-trip-ms
  labels:
    app: wheelsun-trip-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wheelsun-trip-ms
  template:
    metadata:
      labels:
        app: wheelsun-trip-ms
    spec:
      containers:
      - name: wheelsun-trip-ms
        image: ccortesra/wheels
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: wheelsun-trip-ms
  labels:
    app: wheelsun-trip-ms
spec:
  ports:
  - port: 3002
    targetPort: 3002
  selector:
    app: wheelsun-trip-ms
  type: ClusterIP
